### ISSUE TITLE
Help with GA 

### ISSUE THREAD

**Issue by fatihmuaddib** [thieu1995/MHA-TSP#2]
There's a good chance this is an idiot behind the machine error as I am not super familiar with GA or python but I can't get your examples to work with GA. MFO for example works as a drop in all of them but GA makes the interpreter angry. At some point the values I get from GA for pos turns into floats casting them as integers doesn't work for the graphs. I do apologise if this is my short coming and has a obvious solution.
Sorry for the formatting, I am on mobile as I create this issue.
Thanks for the awesome work!

**Comment by thieu1995** [comment]
@fatihmuaddib ,

Have you installed the lastest version of mealpy==2.4.0 ?

I add the code and results for GA here: 
https://github.com/thieu1995/MHA-TSP/blob/main/04_ga_tsp_basic.py

For GA, it has so many strategies and parameters you can turn to get a better results. 
You can check the document here: https://mealpy.readthedocs.io/en/latest/pages/models/mealpy.evolutionary_based.html#module-mealpy.evolutionary_based.GA

For example:

```
model2 = BaseGA(problem_dict1, epoch, pop_size, pc, pm, selection="tournament", k_way=0.4, crossover="multi_points")

model3 = BaseGA(problem_dict1, epoch, pop_size, pc, pm, crossover="one_point", mutation="scramble")

model4 = BaseGA(problem_dict1, epoch, pop_size, pc, pm, crossover="arithmetic", mutation_multipoints=True, mutation="swap")

model5 = BaseGA(problem_dict1, epoch, pop_size, pc, pm, selection="roulette", crossover="multi_points")

model6 = BaseGA(problem_dict1, epoch, pop_size, pc, pm, selection="random", mutation="inversion")

model7 = BaseGA(problem_dict1, epoch, pop_size, pc, pm, crossover="arithmetic", mutation="flip")
```

Best regards,

**Comment by thieu1995** [comment]
@fatihmuaddib ,

Sorry my bad tho. I have checked my code again and see that I'm still using WOA model instead of GA model. 
After test with GA model for this particular problem (TSP). It is also show the error like you've got.

I have to check the code in Mealpy library and found a problem. I forgot to call the function amend_position after the mutation_process. Therefor, for this discrete problem, GA model can't be used. 

I will fix in the new version of Mealpy. You should try algorithms instead of GA. There is like 150 other algorithms you can test with. 

Best regards,

**Comment by fatihmuaddib** [comment]
Well good to know it wasn't my lack of skill. And while it is a great tool to play with meta heuristics. I do have a dead line to use GA. I'll switch to MATLAB for now.

**Comment by thieu1995** [comment]
@fatihmuaddib ,

Have you check the latest version of Mealpy. I've fixed the problem in GA.

**Comment by fatihmuaddib** [comment]
Thanks for the awesome work!
